#!/usr/bin/env bash
#ddev-generated

if [ -z "$STRIPE_API_KEY" ]  || [ -z "$WEBHOOK_SERVICE_NAME" ] || [ -z "$WEBHOOK_SERVICE_PORT" ] || [ -z "$WEBHOOK_ENDPOINT" ] then
    echo "Stripe API key, webhook service and port are required"
    echo "STRIPE_API_KEY=${STRIPE_API_KEY}\nWEBHOOK_SERVICE_NAME=${WEBHOOK_SERVICE_NAME}\nWEBHOOK_SERVICE_PORT=${WEBHOOK_SERVICE_PORT}\nWEBHOOK_ENDPOINT=${WEBHOOK_ENDPOINT}"
    exit 1
fi
    echo "Stripe proxy setup successful"
    echo "STRIPE_API_KEY=${STRIPE_API_KEY}\nWEBHOOK_SERVICE_NAME=${WEBHOOK_SERVICE_NAME}\nWEBHOOK_SERVICE_PORT=${WEBHOOK_SERVICE_PORT}\nWEBHOOK_ENDPOINT=${WEBHOOK_ENDPOINT}"

